version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: mrps_game
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432